# SPDX-License-Identifier: 0BSD

name: Windows-2022-CI

jobs:
  scripts:
    runs-on: windows-2022
    steps:
      - run: echo "This step runs in CMD on Windows explicitly"
        shell: cmd
        working-directory: windows
