# SPDX-License-Identifier: 0BSD

name: Windows-2022-CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows running workflow manually
  workflow_dispatch:
    inputs:
      publishbuilds:
        required: false
        description: Publish Builds?
        type: boolean
        default: false

jobs:
  VS2022:
    strategy:
      matrix:
        platform: [x64, Win32]
        toolset: [v143, ClangCL]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: build-with-vs2022.bat ${{ matrix.platform }} ${{ matrix.toolset }} build
        name: Build (Visual Studio 2022, ${{ matrix.platform }}, ${{ matrix.toolset }})
        shell: cmd
        working-directory: windows
      - run: build-with-vs2022.bat ${{ matrix.platform }} ${{ matrix.toolset }} test
        name: Test (Visual Studio 2022, ${{ matrix.platform }}, ${{ matrix.toolset }})
        shell: cmd
        working-directory: windows
      - name: VS2022 Build Artifacts
        if: inputs.publishbuilds && (matrix.toolset == 'ClangCL')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-${{ matrix.platform }}
          path: |
            windows/build*/Release
